module.exports = {
    EDIT_SUCCESS: 'Cập nhập thành công!',
    ADD_SUCCESS: 'thêm mới thành công!',
    STATUS_SUCCESS: 'Cập nhập status thành công!',
    GROUPS_ACP_SUCCESS: 'Cập nhập groups_acp thành công!',
    SPECIAL_SUCCESS: 'Cập nhập special thành công!',
    STATUS_MULTI_SUCCESS: 'Cập nhập %d status thành công!',
    DELETE_SUCCESS: 'Xóa thành công!', 
    ORDERING_SUCCESS:'Thay đổi ordering thành công!',
    DELETE_MULTI_SUCCESS: 'Xóa %d phần tử thành công!', 
    ERROR_NAME: 'chiều dài từ %d đến %d kí tự',
    ERROR_ORDERING: 'Phải là số nguyên lớn hơn %d và bé hơn %d',
    ERROR_STATUS: 'Status phải khác rỗng',
    ERROR_GROUPS_ACP: 'Groups_acp phải khác rỗng',
    ERROR_SPECIAL: 'Special phải khác rỗng',
    ERROR_GROUPS: 'Groups phải khác rỗng',
    ERROR_UPLOADS_AVATAR: 'vui lòng chọn avatar',
    ERROR_UPLOADS_THUMB: 'vui lòng chọn thumb',
    ERROR_LIMIT: 'Kích thước file không phù hợp',
    ERROR_CATEGORY: 'Category phải khác rỗng',
    ERROR_USERNAME: 'chiều dài username từ %d đến %d kí tự',
    ERROR_PASSWORD: 'chiều dài mật khẩu từ %d đến %d kí tự',
    ERROR_NEW_PASSWORD: 'chiều dài mật khẩu mới từ %d đến %d kí tự',
    ERROR_LOGIN_USERNAME_NOTEXIST: 'Username không tồn tại',
    ERROR_LOGIN_PASSWORD_INCORRECT: 'Mật khẩu không chính xác',
    ERROR_LOGIN: 'Thông tin đăng nhập không chính xác',
    SUCCESS_CONTACT: 'Gửi thông tin liên hệ thành công',
    ERROR_NAMESHAKE: 'Name đã tồn tại',
    ERROR_USERNAMESHAKE: 'Username đã tồn tại',
    ERROR_VIEW_TYPE: 'View Type phải khác rỗng',
    ERROR_DUPLICATE_PASSWORD: 'Mật khẩu không được trùng với mật khẩu cũ',
    ERROR_WRONG_PASSWORD: 'Mật khẩu cũ không chính xác',
    ERROR_CONFIRM_PASSWORD_EMPTY: 'Vui lòng xác nhận lại mật khẩu mới',
    ERROR_CONFIRM_PASSWORD: 'Mật khẩu không khớp với mật khẩu trên'
}